name: Build

on:
  push:
    branches:
      - main
      - build
  release:
    types:
      - published

jobs:
  build_wheels_windows:
    name: Build wheel on windows-latest/${{matrix.arch}}/${{matrix.python_tag}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [auto32, auto64]
        python_tag: ["pp37-*", "pp38-*", "pp39-*"]
        exclude:
          # PyPy only supports x86_64 on Windows
          - arch: auto32
            python_tag: "pp37-*"
          - arch: auto32
            python_tag: "pp38-*"
          - arch: auto32
            python_tag: "pp39-*"
    env:
      CIBW_BUILD: ${{matrix.python_tag}}
      CIBW_ARCHS: ${{matrix.arch}}
      CIBW_TEST_REQUIRES: pytest hypothesis pandas
      CIBW_TEST_COMMAND: pytest {package}/tests
      CIBW_TEST_COMMAND_LINUX: "{package}/tools/seg_wrapper.sh pytest {package}/tests"
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
